# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea96c4554bbee182fbb4f58c255e52667059d7b736d4c7bfe61da8c39a2779d9949d40534dc82f74c6b044a7a66facedc35db79ffefc7b0efe5bf34478a603b

test:
  secret_key_base: 624171b12849201a7024d84ceb7fb26050a14a416aea7b895de929b35239a2ed2430309b2ba67caa24f54b3506051ab47106d5106e2ba9e9bb083355ca0ecc65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
